export const actionTypes = {
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    SHOW_PRODUCT_DETAILS: 'SHOW_PRODUCT_DETAILS',
    GET_DATA_FROM_LOCALSTORAGE: 'GET_DATA_FROM_LOCALSTORAGE',
    SAVE_DATA_TO_LOCALSTORAGE: 'SAVE_DATA_TO_LOCALSTORAGE',
}
